/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model;


import BoBaPop.Model.tables.Bills;
import BoBaPop.Model.tables.Drinks;
import BoBaPop.Model.tables.Drinktypes;
import BoBaPop.Model.tables.Items;
import BoBaPop.Model.tables.Tables;
import BoBaPop.Model.tables.Users;
import BoBaPop.Model.tables.VwBillDetails;
import BoBaPop.Model.tables.VwBillStatistic;
import BoBaPop.Model.tables.VwDrinks;
import BoBaPop.Model.tables.VwItems;
import BoBaPop.Model.tables.VwSumDrinkByBill;
import BoBaPop.Model.tables.VwTodayBills;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbMilktea extends SchemaImpl {

    private static final long serialVersionUID = 1427973178;

    /**
     * The reference instance of <code>db_milktea</code>
     */
    public static final DbMilktea DB_MILKTEA = new DbMilktea();

    /**
     * InnoDB free: 23552 kB; (`TableID`) REFER `db_milktea/tables`(`TableID`)
     */
    public final Bills BILLS = BoBaPop.Model.tables.Bills.BILLS;

    /**
     * InnoDB free: 23552 kB; (`DrinkTypeID`) REFER `db_milktea/drinktypes`(`DrinkTypeI
     */
    public final Drinks DRINKS = BoBaPop.Model.tables.Drinks.DRINKS;

    /**
     * InnoDB free: 23552 kB
     */
    public final Drinktypes DRINKTYPES = BoBaPop.Model.tables.Drinktypes.DRINKTYPES;

    /**
     * InnoDB free: 23552 kB; (`BillID`) REFER `db_milktea/bills`(`BillID`); (`DrinkID`
     */
    public final Items ITEMS = BoBaPop.Model.tables.Items.ITEMS;

    /**
     * InnoDB free: 23552 kB
     */
    public final Tables TABLES = BoBaPop.Model.tables.Tables.TABLES;

    /**
     * InnoDB free: 23552 kB
     */
    public final Users USERS = BoBaPop.Model.tables.Users.USERS;

    /**
     * VIEW
     */
    public final VwBillDetails VW_BILL_DETAILS = BoBaPop.Model.tables.VwBillDetails.VW_BILL_DETAILS;

    /**
     * VIEW
     */
    public final VwBillStatistic VW_BILL_STATISTIC = BoBaPop.Model.tables.VwBillStatistic.VW_BILL_STATISTIC;

    /**
     * VIEW
     */
    public final VwDrinks VW_DRINKS = BoBaPop.Model.tables.VwDrinks.VW_DRINKS;

    /**
     * VIEW
     */
    public final VwItems VW_ITEMS = BoBaPop.Model.tables.VwItems.VW_ITEMS;

    /**
     * VIEW
     */
    public final VwSumDrinkByBill VW_SUM_DRINK_BY_BILL = BoBaPop.Model.tables.VwSumDrinkByBill.VW_SUM_DRINK_BY_BILL;

    /**
     * VIEW
     */
    public final VwTodayBills VW_TODAY_BILLS = BoBaPop.Model.tables.VwTodayBills.VW_TODAY_BILLS;

    /**
     * No further instances allowed
     */
    private DbMilktea() {
        super("db_milktea", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bills.BILLS,
            Drinks.DRINKS,
            Drinktypes.DRINKTYPES,
            Items.ITEMS,
            Tables.TABLES,
            Users.USERS,
            VwBillDetails.VW_BILL_DETAILS,
            VwBillStatistic.VW_BILL_STATISTIC,
            VwDrinks.VW_DRINKS,
            VwItems.VW_ITEMS,
            VwSumDrinkByBill.VW_SUM_DRINK_BY_BILL,
            VwTodayBills.VW_TODAY_BILLS);
    }
}
