/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.DbMilktea;
import BoBaPop.Model.Indexes;
import BoBaPop.Model.Keys;
import BoBaPop.Model.tables.records.DrinktypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * InnoDB free: 23552 kB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drinktypes extends TableImpl<DrinktypesRecord> {

    private static final long serialVersionUID = 1035330328;

    /**
     * The reference instance of <code>db_milktea.drinktypes</code>
     */
    public static final Drinktypes DRINKTYPES = new Drinktypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrinktypesRecord> getRecordType() {
        return DrinktypesRecord.class;
    }

    /**
     * The column <code>db_milktea.drinktypes.DrinkTypeID</code>.
     */
    public final TableField<DrinktypesRecord, Integer> DRINKTYPEID = createField("DrinkTypeID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>db_milktea.drinktypes.DrinkTypeName</code>.
     */
    public final TableField<DrinktypesRecord, String> DRINKTYPENAME = createField("DrinkTypeName", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>db_milktea.drinktypes</code> table reference
     */
    public Drinktypes() {
        this(DSL.name("drinktypes"), null);
    }

    /**
     * Create an aliased <code>db_milktea.drinktypes</code> table reference
     */
    public Drinktypes(String alias) {
        this(DSL.name(alias), DRINKTYPES);
    }

    /**
     * Create an aliased <code>db_milktea.drinktypes</code> table reference
     */
    public Drinktypes(Name alias) {
        this(alias, DRINKTYPES);
    }

    private Drinktypes(Name alias, Table<DrinktypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Drinktypes(Name alias, Table<DrinktypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "InnoDB free: 23552 kB");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMilktea.DB_MILKTEA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DRINKTYPES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DrinktypesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DRINKTYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DrinktypesRecord> getPrimaryKey() {
        return Keys.KEY_DRINKTYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DrinktypesRecord>> getKeys() {
        return Arrays.<UniqueKey<DrinktypesRecord>>asList(Keys.KEY_DRINKTYPES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Drinktypes as(String alias) {
        return new Drinktypes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Drinktypes as(Name alias) {
        return new Drinktypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Drinktypes rename(String name) {
        return new Drinktypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Drinktypes rename(Name name) {
        return new Drinktypes(name, null);
    }
}
