/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.DbMilktea;
import BoBaPop.Model.tables.records.VwBillDetailsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBillDetails extends TableImpl<VwBillDetailsRecord> {

    private static final long serialVersionUID = -1071210164;

    /**
     * The reference instance of <code>db_milktea.vw_bill_details</code>
     */
    public static final VwBillDetails VW_BILL_DETAILS = new VwBillDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VwBillDetailsRecord> getRecordType() {
        return VwBillDetailsRecord.class;
    }

    /**
     * The column <code>db_milktea.vw_bill_details.BillID</code>.
     */
    public final TableField<VwBillDetailsRecord, Integer> BILLID = createField("BillID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.TableID</code>.
     */
    public final TableField<VwBillDetailsRecord, Integer> TABLEID = createField("TableID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.OrderTime</code>.
     */
    public final TableField<VwBillDetailsRecord, Timestamp> ORDERTIME = createField("OrderTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.TableName</code>.
     */
    public final TableField<VwBillDetailsRecord, String> TABLENAME = createField("TableName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.GrandTotal</code>.
     */
    public final TableField<VwBillDetailsRecord, Double> GRANDTOTAL = createField("GrandTotal", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.IsPaid</code>.
     */
    public final TableField<VwBillDetailsRecord, Byte> ISPAID = createField("IsPaid", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>db_milktea.vw_bill_details.IsStaying</code>.
     */
    public final TableField<VwBillDetailsRecord, Byte> ISSTAYING = createField("IsStaying", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>db_milktea.vw_bill_details</code> table reference
     */
    public VwBillDetails() {
        this(DSL.name("vw_bill_details"), null);
    }

    /**
     * Create an aliased <code>db_milktea.vw_bill_details</code> table reference
     */
    public VwBillDetails(String alias) {
        this(DSL.name(alias), VW_BILL_DETAILS);
    }

    /**
     * Create an aliased <code>db_milktea.vw_bill_details</code> table reference
     */
    public VwBillDetails(Name alias) {
        this(alias, VW_BILL_DETAILS);
    }

    private VwBillDetails(Name alias, Table<VwBillDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VwBillDetails(Name alias, Table<VwBillDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMilktea.DB_MILKTEA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetails as(String alias) {
        return new VwBillDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetails as(Name alias) {
        return new VwBillDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBillDetails rename(String name) {
        return new VwBillDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBillDetails rename(Name name) {
        return new VwBillDetails(name, null);
    }
}
