/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.DbMilktea;
import BoBaPop.Model.tables.records.VwBillStatisticRecord;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBillStatistic extends TableImpl<VwBillStatisticRecord> {

    private static final long serialVersionUID = 1782905758;

    /**
     * The reference instance of <code>db_milktea.vw_bill_statistic</code>
     */
    public static final VwBillStatistic VW_BILL_STATISTIC = new VwBillStatistic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VwBillStatisticRecord> getRecordType() {
        return VwBillStatisticRecord.class;
    }

    /**
     * The column <code>db_milktea.vw_bill_statistic.BillID</code>.
     */
    public final TableField<VwBillStatisticRecord, Integer> BILLID = createField("BillID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_bill_statistic.TableID</code>.
     */
    public final TableField<VwBillStatisticRecord, Integer> TABLEID = createField("TableID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_bill_statistic.OrderTime</code>.
     */
    public final TableField<VwBillStatisticRecord, Timestamp> ORDERTIME = createField("OrderTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>db_milktea.vw_bill_statistic.TableName</code>.
     */
    public final TableField<VwBillStatisticRecord, String> TABLENAME = createField("TableName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>db_milktea.vw_bill_statistic.GrandTotal</code>.
     */
    public final TableField<VwBillStatisticRecord, Double> GRANDTOTAL = createField("GrandTotal", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>db_milktea.vw_bill_statistic.SumDrink</code>.
     */
    public final TableField<VwBillStatisticRecord, BigInteger> SUMDRINK = createField("SumDrink", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(32), this, "");

    /**
     * Create a <code>db_milktea.vw_bill_statistic</code> table reference
     */
    public VwBillStatistic() {
        this(DSL.name("vw_bill_statistic"), null);
    }

    /**
     * Create an aliased <code>db_milktea.vw_bill_statistic</code> table reference
     */
    public VwBillStatistic(String alias) {
        this(DSL.name(alias), VW_BILL_STATISTIC);
    }

    /**
     * Create an aliased <code>db_milktea.vw_bill_statistic</code> table reference
     */
    public VwBillStatistic(Name alias) {
        this(alias, VW_BILL_STATISTIC);
    }

    private VwBillStatistic(Name alias, Table<VwBillStatisticRecord> aliased) {
        this(alias, aliased, null);
    }

    private VwBillStatistic(Name alias, Table<VwBillStatisticRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMilktea.DB_MILKTEA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatistic as(String alias) {
        return new VwBillStatistic(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatistic as(Name alias) {
        return new VwBillStatistic(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBillStatistic rename(String name) {
        return new VwBillStatistic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBillStatistic rename(Name name) {
        return new VwBillStatistic(name, null);
    }
}
