/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.DbMilktea;
import BoBaPop.Model.tables.records.VwSumDrinkByBillRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwSumDrinkByBill extends TableImpl<VwSumDrinkByBillRecord> {

    private static final long serialVersionUID = 1117534295;

    /**
     * The reference instance of <code>db_milktea.vw_sum_drink_by_bill</code>
     */
    public static final VwSumDrinkByBill VW_SUM_DRINK_BY_BILL = new VwSumDrinkByBill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VwSumDrinkByBillRecord> getRecordType() {
        return VwSumDrinkByBillRecord.class;
    }

    /**
     * The column <code>db_milktea.vw_sum_drink_by_bill.BillID</code>.
     */
    public final TableField<VwSumDrinkByBillRecord, Integer> BILLID = createField("BillID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_sum_drink_by_bill.SumDrink</code>.
     */
    public final TableField<VwSumDrinkByBillRecord, BigInteger> SUMDRINK = createField("SumDrink", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(32), this, "");

    /**
     * Create a <code>db_milktea.vw_sum_drink_by_bill</code> table reference
     */
    public VwSumDrinkByBill() {
        this(DSL.name("vw_sum_drink_by_bill"), null);
    }

    /**
     * Create an aliased <code>db_milktea.vw_sum_drink_by_bill</code> table reference
     */
    public VwSumDrinkByBill(String alias) {
        this(DSL.name(alias), VW_SUM_DRINK_BY_BILL);
    }

    /**
     * Create an aliased <code>db_milktea.vw_sum_drink_by_bill</code> table reference
     */
    public VwSumDrinkByBill(Name alias) {
        this(alias, VW_SUM_DRINK_BY_BILL);
    }

    private VwSumDrinkByBill(Name alias, Table<VwSumDrinkByBillRecord> aliased) {
        this(alias, aliased, null);
    }

    private VwSumDrinkByBill(Name alias, Table<VwSumDrinkByBillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMilktea.DB_MILKTEA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwSumDrinkByBill as(String alias) {
        return new VwSumDrinkByBill(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwSumDrinkByBill as(Name alias) {
        return new VwSumDrinkByBill(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VwSumDrinkByBill rename(String name) {
        return new VwSumDrinkByBill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VwSumDrinkByBill rename(Name name) {
        return new VwSumDrinkByBill(name, null);
    }
}
