/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.DbMilktea;
import BoBaPop.Model.tables.records.VwTodayBillsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwTodayBills extends TableImpl<VwTodayBillsRecord> {

    private static final long serialVersionUID = 628239212;

    /**
     * The reference instance of <code>db_milktea.vw_today_bills</code>
     */
    public static final VwTodayBills VW_TODAY_BILLS = new VwTodayBills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VwTodayBillsRecord> getRecordType() {
        return VwTodayBillsRecord.class;
    }

    /**
     * The column <code>db_milktea.vw_today_bills.BillID</code>.
     */
    public final TableField<VwTodayBillsRecord, Integer> BILLID = createField("BillID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.OrderTime</code>.
     */
    public final TableField<VwTodayBillsRecord, Timestamp> ORDERTIME = createField("OrderTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.IsPaid</code>.
     */
    public final TableField<VwTodayBillsRecord, Byte> ISPAID = createField("IsPaid", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.IsStaying</code>.
     */
    public final TableField<VwTodayBillsRecord, Byte> ISSTAYING = createField("IsStaying", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.GrandTotal</code>.
     */
    public final TableField<VwTodayBillsRecord, Double> GRANDTOTAL = createField("GrandTotal", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.TableID</code>.
     */
    public final TableField<VwTodayBillsRecord, Integer> TABLEID = createField("TableID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>db_milktea.vw_today_bills.TableName</code>.
     */
    public final TableField<VwTodayBillsRecord, String> TABLENAME = createField("TableName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>db_milktea.vw_today_bills</code> table reference
     */
    public VwTodayBills() {
        this(DSL.name("vw_today_bills"), null);
    }

    /**
     * Create an aliased <code>db_milktea.vw_today_bills</code> table reference
     */
    public VwTodayBills(String alias) {
        this(DSL.name(alias), VW_TODAY_BILLS);
    }

    /**
     * Create an aliased <code>db_milktea.vw_today_bills</code> table reference
     */
    public VwTodayBills(Name alias) {
        this(alias, VW_TODAY_BILLS);
    }

    private VwTodayBills(Name alias, Table<VwTodayBillsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VwTodayBills(Name alias, Table<VwTodayBillsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbMilktea.DB_MILKTEA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBills as(String alias) {
        return new VwTodayBills(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBills as(Name alias) {
        return new VwTodayBills(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VwTodayBills rename(String name) {
        return new VwTodayBills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VwTodayBills rename(Name name) {
        return new VwTodayBills(name, null);
    }
}
