/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.routines;


import BoBaPop.Model.DbMilktea;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FtIsStaying extends AbstractRoutine<Byte> {

    private static final long serialVersionUID = -1279917159;

    /**
     * The parameter <code>db_milktea.ft_Is_Staying.RETURN_VALUE</code>.
     */
    public static final Parameter<Byte> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TINYINT, false, false);

    /**
     * The parameter <code>db_milktea.ft_Is_Staying.TableID</code>.
     */
    public static final Parameter<Integer> TABLEID = createParameter("TableID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public FtIsStaying() {
        super("ft_Is_Staying", DbMilktea.DB_MILKTEA, org.jooq.impl.SQLDataType.TINYINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TABLEID);
    }

    /**
     * Set the <code>TableID</code> parameter IN value to the routine
     */
    public void setTableid(Integer value) {
        setValue(TABLEID, value);
    }

    /**
     * Set the <code>TableID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTableid(Field<Integer> field) {
        setField(TABLEID, field);
    }
}
