/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.routines;


import BoBaPop.Model.DbMilktea;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpDeleteTable extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -99100295;

    /**
     * The parameter <code>db_milktea.sp_delete_table.TableID</code>.
     */
    public static final Parameter<Integer> TABLEID = createParameter("TableID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public SpDeleteTable() {
        super("sp_delete_table", DbMilktea.DB_MILKTEA);

        addInParameter(TABLEID);
    }

    /**
     * Set the <code>TableID</code> parameter IN value to the routine
     */
    public void setTableid(Integer value) {
        setValue(TABLEID, value);
    }
}
