/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.routines;


import BoBaPop.Model.DbMilktea;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpPaying extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -626799534;

    /**
     * The parameter <code>db_milktea.sp_paying.Bill_ID</code>.
     */
    public static final Parameter<Integer> BILL_ID = createParameter("Bill_ID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public SpPaying() {
        super("sp_paying", DbMilktea.DB_MILKTEA);

        addInParameter(BILL_ID);
    }

    /**
     * Set the <code>Bill_ID</code> parameter IN value to the routine
     */
    public void setBillId(Integer value) {
        setValue(BILL_ID, value);
    }
}
