/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.Bills;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * InnoDB free: 23552 kB; (`TableID`) REFER `db_milktea/tables`(`TableID`)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillsRecord extends UpdatableRecordImpl<BillsRecord> implements Record6<Integer, Timestamp, Double, Byte, Byte, Integer> {

    private static final long serialVersionUID = 1749559531;

    /**
     * Setter for <code>db_milktea.bills.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_milktea.bills.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_milktea.bills.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_milktea.bills.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>db_milktea.bills.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_milktea.bills.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>db_milktea.bills.IsPaid</code>.
     */
    public void setIspaid(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_milktea.bills.IsPaid</code>.
     */
    public Byte getIspaid() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>db_milktea.bills.IsStaying</code>.
     */
    public void setIsstaying(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_milktea.bills.IsStaying</code>.
     */
    public Byte getIsstaying() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>db_milktea.bills.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_milktea.bills.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Double, Byte, Byte, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Double, Byte, Byte, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Bills.BILLS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Bills.BILLS.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Bills.BILLS.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Bills.BILLS.ISPAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Bills.BILLS.ISSTAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Bills.BILLS.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value2(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value3(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value4(Byte value) {
        setIspaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value5(Byte value) {
        setIsstaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value6(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord values(Integer value1, Timestamp value2, Double value3, Byte value4, Byte value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillsRecord
     */
    public BillsRecord() {
        super(Bills.BILLS);
    }

    /**
     * Create a detached, initialised BillsRecord
     */
    public BillsRecord(Integer billid, Timestamp ordertime, Double grandtotal, Byte ispaid, Byte isstaying, Integer tableid) {
        super(Bills.BILLS);

        set(0, billid);
        set(1, ordertime);
        set(2, grandtotal);
        set(3, ispaid);
        set(4, isstaying);
        set(5, tableid);
    }
}
