/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwBillDetails;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBillDetailsRecord extends TableRecordImpl<VwBillDetailsRecord> implements Record7<Integer, Integer, Timestamp, String, Double, Byte, Byte> {

    private static final long serialVersionUID = -2141620161;

    /**
     * Setter for <code>db_milktea.vw_bill_details.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.TableName</code>.
     */
    public void setTablename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.TableName</code>.
     */
    public String getTablename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.IsPaid</code>.
     */
    public void setIspaid(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.IsPaid</code>.
     */
    public Byte getIspaid() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_details.IsStaying</code>.
     */
    public void setIsstaying(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_details.IsStaying</code>.
     */
    public Byte getIsstaying() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, String, Double, Byte, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, String, Double, Byte, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwBillDetails.VW_BILL_DETAILS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VwBillDetails.VW_BILL_DETAILS.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VwBillDetails.VW_BILL_DETAILS.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VwBillDetails.VW_BILL_DETAILS.TABLENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VwBillDetails.VW_BILL_DETAILS.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return VwBillDetails.VW_BILL_DETAILS.ISPAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return VwBillDetails.VW_BILL_DETAILS.ISSTAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value2(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value3(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value4(String value) {
        setTablename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value5(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value6(Byte value) {
        setIspaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord value7(Byte value) {
        setIsstaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillDetailsRecord values(Integer value1, Integer value2, Timestamp value3, String value4, Double value5, Byte value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwBillDetailsRecord
     */
    public VwBillDetailsRecord() {
        super(VwBillDetails.VW_BILL_DETAILS);
    }

    /**
     * Create a detached, initialised VwBillDetailsRecord
     */
    public VwBillDetailsRecord(Integer billid, Integer tableid, Timestamp ordertime, String tablename, Double grandtotal, Byte ispaid, Byte isstaying) {
        super(VwBillDetails.VW_BILL_DETAILS);

        set(0, billid);
        set(1, tableid);
        set(2, ordertime);
        set(3, tablename);
        set(4, grandtotal);
        set(5, ispaid);
        set(6, isstaying);
    }
}
