/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwBillStatistic;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBillStatisticRecord extends TableRecordImpl<VwBillStatisticRecord> implements Record6<Integer, Integer, Timestamp, String, Double, BigInteger> {

    private static final long serialVersionUID = 678388360;

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.TableName</code>.
     */
    public void setTablename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.TableName</code>.
     */
    public String getTablename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>db_milktea.vw_bill_statistic.SumDrink</code>.
     */
    public void setSumdrink(BigInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_milktea.vw_bill_statistic.SumDrink</code>.
     */
    public BigInteger getSumdrink() {
        return (BigInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Timestamp, String, Double, BigInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Timestamp, String, Double, BigInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwBillStatistic.VW_BILL_STATISTIC.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VwBillStatistic.VW_BILL_STATISTIC.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VwBillStatistic.VW_BILL_STATISTIC.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VwBillStatistic.VW_BILL_STATISTIC.TABLENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VwBillStatistic.VW_BILL_STATISTIC.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field6() {
        return VwBillStatistic.VW_BILL_STATISTIC.SUMDRINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component6() {
        return getSumdrink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value6() {
        return getSumdrink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value2(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value3(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value4(String value) {
        setTablename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value5(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord value6(BigInteger value) {
        setSumdrink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBillStatisticRecord values(Integer value1, Integer value2, Timestamp value3, String value4, Double value5, BigInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwBillStatisticRecord
     */
    public VwBillStatisticRecord() {
        super(VwBillStatistic.VW_BILL_STATISTIC);
    }

    /**
     * Create a detached, initialised VwBillStatisticRecord
     */
    public VwBillStatisticRecord(Integer billid, Integer tableid, Timestamp ordertime, String tablename, Double grandtotal, BigInteger sumdrink) {
        super(VwBillStatistic.VW_BILL_STATISTIC);

        set(0, billid);
        set(1, tableid);
        set(2, ordertime);
        set(3, tablename);
        set(4, grandtotal);
        set(5, sumdrink);
    }
}
