/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwDrinks;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwDrinksRecord extends TableRecordImpl<VwDrinksRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1003439094;

    /**
     * Setter for <code>db_milktea.vw_drinks.DrinkID</code>.
     */
    public void setDrinkid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_milktea.vw_drinks.DrinkID</code>.
     */
    public Integer getDrinkid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_milktea.vw_drinks.DrinkName</code>.
     */
    public void setDrinkname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_milktea.vw_drinks.DrinkName</code>.
     */
    public String getDrinkname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_milktea.vw_drinks.DrinkTypeID</code>.
     */
    public void setDrinktypeid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_milktea.vw_drinks.DrinkTypeID</code>.
     */
    public Integer getDrinktypeid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwDrinks.VW_DRINKS.DRINKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VwDrinks.VW_DRINKS.DRINKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VwDrinks.VW_DRINKS.DRINKTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDrinkid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDrinkname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDrinktypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDrinkid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDrinkname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDrinktypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwDrinksRecord value1(Integer value) {
        setDrinkid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwDrinksRecord value2(String value) {
        setDrinkname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwDrinksRecord value3(Integer value) {
        setDrinktypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwDrinksRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwDrinksRecord
     */
    public VwDrinksRecord() {
        super(VwDrinks.VW_DRINKS);
    }

    /**
     * Create a detached, initialised VwDrinksRecord
     */
    public VwDrinksRecord(Integer drinkid, String drinkname, Integer drinktypeid) {
        super(VwDrinks.VW_DRINKS);

        set(0, drinkid);
        set(1, drinkname);
        set(2, drinktypeid);
    }
}
