/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwTodayBills;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwTodayBillsRecord extends TableRecordImpl<VwTodayBillsRecord> implements Record7<Integer, Timestamp, Byte, Byte, Double, Integer, String> {

    private static final long serialVersionUID = -472690331;

    /**
     * Setter for <code>db_milktea.vw_today_bills.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.IsPaid</code>.
     */
    public void setIspaid(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.IsPaid</code>.
     */
    public Byte getIspaid() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.IsStaying</code>.
     */
    public void setIsstaying(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.IsStaying</code>.
     */
    public Byte getIsstaying() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>db_milktea.vw_today_bills.TableName</code>.
     */
    public void setTablename(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_milktea.vw_today_bills.TableName</code>.
     */
    public String getTablename() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Byte, Byte, Double, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Byte, Byte, Double, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwTodayBills.VW_TODAY_BILLS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return VwTodayBills.VW_TODAY_BILLS.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return VwTodayBills.VW_TODAY_BILLS.ISPAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return VwTodayBills.VW_TODAY_BILLS.ISSTAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VwTodayBills.VW_TODAY_BILLS.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return VwTodayBills.VW_TODAY_BILLS.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VwTodayBills.VW_TODAY_BILLS.TABLENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value2(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value3(Byte value) {
        setIspaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value4(Byte value) {
        setIsstaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value5(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value6(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord value7(String value) {
        setTablename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwTodayBillsRecord values(Integer value1, Timestamp value2, Byte value3, Byte value4, Double value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwTodayBillsRecord
     */
    public VwTodayBillsRecord() {
        super(VwTodayBills.VW_TODAY_BILLS);
    }

    /**
     * Create a detached, initialised VwTodayBillsRecord
     */
    public VwTodayBillsRecord(Integer billid, Timestamp ordertime, Byte ispaid, Byte isstaying, Double grandtotal, Integer tableid, String tablename) {
        super(VwTodayBills.VW_TODAY_BILLS);

        set(0, billid);
        set(1, ordertime);
        set(2, ispaid);
        set(3, isstaying);
        set(4, grandtotal);
        set(5, tableid);
        set(6, tablename);
    }
}
